### ISSUE TITLE
Add registerAsync

### ISSUE THREAD

**Issue by gbrlsnchs** [lennykean/nestjs-aws-v4#1]
Many NestJS plugins allow registering modules using a factory. It would be great if this library also allowed that via a `registerAsync` function.

**Comment by lennykean** [comment]
Good suggestion. I’ll add it.

**Comment by lennykean** [comment]
This feature was added in 1.1.0.

**Comment by gbrlsnchs** [comment]
Thank you, @lennykean! Nice one.
